### ISSUE TITLE
which version of  halide-2016-10-22 did  you use?

### ISSUE THREAD

**Issue by lpptree** [PK15946/Load_Image_Halide_Android#1]
Hi, which version of  halide-2016-10-22 did  you use? When using halide-arm64-linux-64 and abiFilters is arm64-v8a,  there is the problem:
/usr/bin/ld: skipping incompatible /home/user/Downloads/halide-arm64-linux-64/halide/bin/libHalide.so when searching for -lHalide
/usr/bin/ld: skipping incompatible /home/user/Downloads/halide-arm64-linux-64/halide/lib/libHalide.a when searching for -lHalide
/usr/bin/ld: cannot find -lHalide

**Comment by PK15946** [comment]
If you are compiling the code on a linux system, please use the halide-linux-64-gccXX-trunk-aa5d5514f179bf0ffe1a2dead0c0eb7300b4069a.tgz(though I have built it myself from source code, but this one should works; if it doesn't, download the source code and follow the instruction to build it).

You don't need halide-arm64-xxxxx unless you are compiling the code on arm-device.

**Comment by lpptree** [comment]
Thanks, i will try it.
